# Generated by Django 4.2.3 on 2023-09-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_variation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation_model',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=200),
        ),
        migrations.AlterField(
            model_name='variation_model',
            name='variation_value',
            field=models.CharField(max_length=200),
        ),
    ]
