# Generated by Django 4.2.3 on 2023-10-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_variation_model_variation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation_model',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=200),
        ),
    ]
