# Generated by Django 4.2.3 on 2023-10-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_registation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registation',
            options={},
        ),
    ]
