# Generated by Django 4.2.3 on 2023-09-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_variation_model_variation_category_and_more'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem_model',
            name='variationfk',
            field=models.ManyToManyField(blank=True, to='Product.variation_model'),
        ),
    ]
